compare_policies:
  policy_a_path: run_Easy_major_reward_update_checkpoint-100
  policy_b_path: run_Easy_major_reward_update_checkpoint-650
experiment:
  base_seed: 462
  baseline_algo: DMMD
  blue_env_lambda: 5.0e-05
  clip_param: 0.2
  current_hardness: easy
  entropy_coeff: 0.01
  eval_iterations: 500
  gamma_epsilon: 0.01
  load_checkpoint: true
  max_steps: 8e6
  min_sampling_duration: 100
  mode: test
  num_agents: 50
  num_locations: 2
  prior_alpha_0: 1.0
  prior_beta_0: 4000.0
  quorum_threshold: 0.7
  red_env_lambda_easy: 0.0001
  red_env_lambda_hard: 6.666666666666667e-05
  test_run_name: run_Easy_stricter_voting_checkpoint-800
  training_iterations: 800
  travel_time: 10
  vf_clip_param: 10.0
rewards:
  r_explore_time_amp: 1.0
  r_uncert_amp: 20
  r_vote_amp: 1.5
  reward_for_correct_decision: 20
  reward_for_timeout: -40
  reward_for_wrong_decision: -35
  solved_bonus_time_decay: 5e-7
testing:
  agents:
  - 10
  - 50
  - 100
  - 200
  - 500
  - 1000
  - 2000
  episodes:
  - 10
  - 20
  - 50
  - 100
  - 500
  - 800
  - 1000
  - 2000
  locations:
  - 2
  - 10
  - 50
  - 100
