experiment:
  num_agents: 5
  num_locations: 2
  lambda_range: [1, 10]
  training: true
  travel_time: 10
  quorum_threshold: 0.7
  max_wait: 20

rewards:
  reward_per_travel_timestep: -0.01
  reward_per_event: -0.5
  reward_per_sampling_timestep: 0.02
  reward_for_correct_decision: 10
  reward_for_wrong_decision: -10
