experiment:
  num_agents: 100
  num_locations: 2
  lambda_range: [1, 10]
  training: true
  travel_time: 10

rewards:
  penalty_per_travel_timestep: 0.1
  penalty_per_event: 1
  reward_per_sampling_timestep: 0.2
